In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split

In [224]:
df = pd.read_csv("Ex1-Class-train.csv")
df

         id     x1     x2 x3 x4 x5     x6     x7     x8     x9    x10  y
0    id-001  22.34   0.56  g  o  u   9.43  25.38 -20.91 -25.84   4.08  B
1    id-002  -2.31   7.36  i  p  y  -3.94    NaN  31.65  12.95   9.82  C
2    id-003 -17.55  -4.09  f  l  v -11.02  -1.77 -17.57  15.98  11.43  D
3    id-004 -13.54  -5.42  g  p  x   4.11   2.22  16.72   9.86  16.43  A
4    id-005  13.39  -3.20  i  l  v   2.23  11.76   1.34   4.16  -6.49  B
..      ...    ...    ... .. .. ..    ...    ...    ...    ...    ... ..
485  id-486  12.54   3.16  h  m  v  -3.49 -16.43  -3.70  -4.12  -2.83  D
486  id-487   8.10  -2.49  i  m  u -10.61  -1.63  -8.81  18.60  10.92  B
487  id-488  13.72 -10.59  i  m  y -32.73  -3.94    NaN   8.97  -8.30  C
488  id-489  -6.12  -6.37  e  m  u  22.34  -4.66 -10.86 -17.77  -0.21  C
489  id-490  -4.73 -10.89  g  n  x -20.01  16.22  -9.36   9.43  -2.02  B

[490 rows x 12 columns]

In [135]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 490 entries, 0 to 489
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      480 non-null    object
 1   x1      480 non-null    float64
 2   x2      480 non-null    float64
 3   x3      480 non-null    object
 4   x4      480 non-null    object
 5   x5      480 non-null    object
 6   x6      480 non-null    float64
 7   x7      480 non-null    float64
 8   x8      480 non-null    float64
 9   x9      480 non-null    float64
 10  x10     480 non-null    float64
 11  y       480 non-null    object
dtypes: float64(7), object(5)
memory usage: 46.1+ KB

In [136]:
import statistics

df["y"].fillna(statistics.mode(df["y"]), inplace=True)
df["x3"].fillna(statistics.mode(df["x3"]), inplace=True)
df["x4"].fillna(statistics.mode(df["x4"]), inplace=True)
df["x5"].fillna(statistics.mode(df["x5"]), inplace=True)

In [138]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 490 entries, 0 to 489
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      480 non-null    object
 1   x1      480 non-null    float64
 2   x2      480 non-null    float64
 3   x3      490 non-null    object
 4   x4      490 non-null    object
 5   x5      490 non-null    object
 6   x6      480 non-null    float64
 7   x7      480 non-null    float64
 8   x8      480 non-null    float64
 9   x9      480 non-null    float64
 10  x10     480 non-null    float64
 11  y       490 non-null    object
dtypes: float64(7), object(5)
memory usage: 46.1+ KB

In [12]:
%matplotlib widget

In [225]:
df.dropna(inplace=True)
df

         id     x1     x2 x3 x4 x5     x6     x7     x8     x9    x10  y
0    id-001  22.34   0.56  g  o  u   9.43  25.38 -20.91 -25.84   4.08  B
2    id-003 -17.55  -4.09  f  l  v -11.02  -1.77 -17.57  15.98  11.43  D
3    id-004 -13.54  -5.42  g  p  x   4.11   2.22  16.72   9.86  16.43  A
4    id-005  13.39  -3.20  i  l  v   2.23  11.76   1.34   4.16  -6.49  B
5    id-006   0.58  12.09  f  l  x -13.59  11.67 -12.12 -12.49  -8.07  A
..      ...    ...    ... .. .. ..    ...    ...    ...    ...    ... ..
484  id-485  -8.77  12.36  g  p  v   1.77   0.16  -1.45  14.18  -2.50  D
485  id-486  12.54   3.16  h  m  v  -3.49 -16.43  -3.70  -4.12  -2.83  D
486  id-487   8.10  -2.49  i  m  u -10.61  -1.63  -8.81  18.60  10.92  B
488  id-489  -6.12  -6.37  e  m  u  22.34  -4.66 -10.86 -17.77  -0.21  C
489  id-490  -4.73 -10.89  g  n  x -20.01  16.22  -9.36   9.43  -2.02  B

[386 rows x 12 columns]

In [226]:
df.reset_index(drop=True, inplace=True) 
df

         id     x1     x2 x3 x4 x5     x6     x7     x8     x9    x10  y
0    id-001  22.34   0.56  g  o  u   9.43  25.38 -20.91 -25.84   4.08  B
1    id-003 -17.55  -4.09  f  l  v -11.02  -1.77 -17.57  15.98  11.43  D
2    id-004 -13.54  -5.42  g  p  x   4.11   2.22  16.72   9.86  16.43  A
3    id-005  13.39  -3.20  i  l  v   2.23  11.76   1.34   4.16  -6.49  B
4    id-006   0.58  12.09  f  l  x -13.59  11.67 -12.12 -12.49  -8.07  A
..      ...    ...    ... .. .. ..    ...    ...    ...    ...    ... ..
381  id-485  -8.77  12.36  g  p  v   1.77   0.16  -1.45  14.18  -2.50  D
382  id-486  12.54   3.16  h  m  v  -3.49 -16.43  -3.70  -4.12  -2.83  D
383  id-487   8.10  -2.49  i  m  u -10.61  -1.63  -8.81  18.60  10.92  B
384  id-489  -6.12  -6.37  e  m  u  22.34  -4.66 -10.86 -17.77  -0.21  C
385  id-490  -4.73 -10.89  g  n  x -20.01  16.22  -9.36   9.43  -2.02  B

[386 rows x 12 columns]

In [227]:
# input
x = df.iloc[:, 1:-1]
# output
y = df.iloc[:, -1]

In [142]:
from sklearn.preprocessing import OrdinalEncoder

enc = OrdinalEncoder()
enc.fit(x[["x3", "x4", "x5"]])

OrdinalEncoder()

In [143]:
enc.categories_

[array(['e', 'f', 'g', 'h', 'i'], dtype=object),
 array(['l', 'm', 'n', 'o', 'p'], dtype=object),
 array(['u', 'v', 'w', 'x', 'y'], dtype=object)]

In [144]:
arr = pd.DataFrame(enc.transform(x[["x3", "x4", "x5"]]), columns=["x3", "x4", "x5"])
arr

      x3   x4   x5
0    2.0  3.0  0.0
1    4.0  4.0  4.0
2    1.0  0.0  1.0
3    2.0  4.0  3.0
4    4.0  0.0  1.0
..   ...  ...  ...
485  3.0  1.0  1.0
486  4.0  1.0  0.0
487  4.0  1.0  4.0
488  0.0  1.0  0.0
489  2.0  2.0  3.0

[490 rows x 3 columns]

In [149]:
x[["x3", "x4", "x5"]] = arr
x["x4"] = x["x4"] + 5
x["x5"] = x["x5"] + 10
x

        x1     x2   x3   x4    x5     x6     x7     x8     x9    x10
0    22.34   0.56  2.0  8.0  10.0   9.43  25.38 -20.91 -25.84   4.08
1    -2.31   7.36  4.0  9.0  14.0  -3.94    NaN  31.65  12.95   9.82
2   -17.55  -4.09  1.0  5.0  11.0 -11.02  -1.77 -17.57  15.98  11.43
3   -13.54  -5.42  2.0  9.0  13.0   4.11   2.22  16.72   9.86  16.43
4    13.39  -3.20  4.0  5.0  11.0   2.23  11.76   1.34   4.16  -6.49
..     ...    ...  ...  ...   ...    ...    ...    ...    ...    ...
485  12.54   3.16  3.0  6.0  11.0  -3.49 -16.43  -3.70  -4.12  -2.83
486   8.10  -2.49  4.0  6.0  10.0 -10.61  -1.63  -8.81  18.60  10.92
487  13.72 -10.59  4.0  6.0  14.0 -32.73  -3.94    NaN   8.97  -8.30
488  -6.12  -6.37  0.0  6.0  10.0  22.34  -4.66 -10.86 -17.77  -0.21
489  -4.73 -10.89  2.0  7.0  13.0 -20.01  16.22  -9.36   9.43  -2.02

[490 rows x 10 columns]

In [ ]:
x = x.drop(["x3","x4","x5"], axis=1)

In [232]:
x

        x1     x2     x6     x7     x8     x9    x10
0    22.34   0.56   9.43  25.38 -20.91 -25.84   4.08
1   -17.55  -4.09 -11.02  -1.77 -17.57  15.98  11.43
2   -13.54  -5.42   4.11   2.22  16.72   9.86  16.43
3    13.39  -3.20   2.23  11.76   1.34   4.16  -6.49
4     0.58  12.09 -13.59  11.67 -12.12 -12.49  -8.07
..     ...    ...    ...    ...    ...    ...    ...
381  -8.77  12.36   1.77   0.16  -1.45  14.18  -2.50
382  12.54   3.16  -3.49 -16.43  -3.70  -4.12  -2.83
383   8.10  -2.49 -10.61  -1.63  -8.81  18.60  10.92
384  -6.12  -6.37  22.34  -4.66 -10.86 -17.77  -0.21
385  -4.73 -10.89 -20.01  16.22  -9.36   9.43  -2.02

[386 rows x 7 columns]

In [243]:
y

0      B
1      D
2      A
3      B
4      A
      ..
381    D
382    D
383    B
384    C
385    B
Name: y, Length: 386, dtype: object

In [248]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25)

print(f"Train data shape of x = {x_train.shape} and y = {y_train.shape}")
print(f"Test data shape of x = {x_test.shape} and y = {y_test.shape}")

Train data shape of x = (289, 7) and y = (289,)
Test data shape of x = (97, 7) and y = (97,)

**DECISION TREE**

In [235]:
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier

tree_model = DecisionTreeClassifier()
tree_model.fit(x_train, y_train)

DecisionTreeClassifier()

In [ ]:
print(tree.export_text(tree_model))

In [236]:
y_pred = tree_model.predict(x_test)
y_pred

array(['B', 'A', 'D', 'A', 'B', 'B', 'A', 'D', 'C', 'C', 'D', 'D', 'B',
       'B', 'A', 'C', 'A', 'A', 'D', 'D', 'C', 'B', 'C', 'A', 'A', 'A',
       'A', 'D', 'B', 'C', 'C', 'A', 'C', 'D', 'C', 'C', 'B', 'A', 'A',
       'A', 'D', 'C', 'B', 'A', 'A', 'C', 'B', 'D', 'A', 'A', 'D', 'D',
       'B', 'D', 'C', 'C', 'A', 'D', 'A', 'A', 'A', 'C', 'D', 'A', 'C',
       'D', 'A', 'D', 'D', 'A', 'A', 'A', 'C', 'D', 'D', 'C', 'C', 'D'],
      dtype=object)

In [237]:
from sklearn.metrics import accuracy_score

acc = accuracy_score(y_test, y_pred)
acc

0.6410256410256411

In [238]:
from sklearn.metrics import precision_recall_fscore_support

prf = precision_recall_fscore_support(y_test, y_pred, average = "weighted")
prf

(0.6514518619781777, 0.6410256410256411, 0.6381915263604228, None)

**RANDOM FORREST**

In [249]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(n_estimators=288, max_depth=17)
rf_model.fit(x_train, y_train)

RandomForestClassifier(max_depth=17, n_estimators=288)

In [250]:
y_pred = rf_model.predict(x_test)
y_pred

array(['C', 'A', 'B', 'A', 'B', 'A', 'D', 'B', 'A', 'D', 'A', 'D', 'A',
       'B', 'D', 'A', 'B', 'C', 'A', 'C', 'D', 'A', 'D', 'C', 'B', 'D',
       'D', 'A', 'D', 'B', 'C', 'B', 'C', 'D', 'A', 'A', 'D', 'D', 'C',
       'B', 'A', 'B', 'B', 'B', 'B', 'D', 'B', 'D', 'D', 'A', 'B', 'D',
       'A', 'B', 'B', 'A', 'D', 'C', 'C', 'B', 'B', 'A', 'B', 'A', 'B',
       'D', 'C', 'B', 'A', 'C', 'B', 'C', 'B', 'C', 'C', 'D', 'A', 'B',
       'B', 'D', 'C', 'D', 'C', 'A', 'D', 'A', 'B', 'D', 'D', 'B', 'D',
       'D', 'D', 'C', 'A', 'A', 'C'], dtype=object)

In [251]:
acc = accuracy_score(y_test, y_pred)
acc

0.7216494845360825

In [252]:
prf = precision_recall_fscore_support(y_test, y_pred, average = "weighted")
prf

(0.7330496918125785, 0.7216494845360825, 0.7150874047512327, None)

In [255]:
from sklearn.model_selection import KFold

kf = KFold(n_splits = 5)
acc_list = []

for train_index, test_index in kf.split(x):
  X_train, X_test = x.loc[train_index], x.loc[test_index]
  y_train, y_test = y.loc[train_index], y.loc[test_index]

  model = RandomForestClassifier(n_estimators=288, max_depth=17)
  model.fit(X_train, y_train)

  y_pred = model.predict(X_test)
  acc = accuracy_score(y_test, y_pred)
  acc_list.append(acc)

print("------------------------------------")
print("Random Forest")
print(" Mean Accuracy :", np.mean(acc_list))

------------------------------------
Random Forest
 Mean Accuracy : 0.7254079254079254

**Test Model**

In [210]:
df_unseen = pd.read_csv("Ex1-Class-unseen.csv")
df_unseen

    id     x1     x2 x3 x4 x5     x6     x7     x8     x9    x10
0  Q01  -9.06  -6.24  e  l  y -17.25  13.47  -9.97  -9.37   8.36
1  Q02 -10.93  -0.05  e  l  y  -5.69  -6.59  -8.48 -17.99  -8.84
2  Q03  -9.06   0.07  e  p  y -26.56   7.69 -15.15  -9.59 -21.66
3  Q04   5.94  10.92  h  n  v  36.03  -2.95  22.84 -16.83   7.12
4  Q05  27.87  37.07  i  m  u   1.32   0.71 -17.56  -6.77   4.05
5  Q06  -9.49   1.17  g  n  u  31.70 -18.75   3.05   5.02  19.09
6  Q07   1.78  -1.09  e  l  u  41.81   8.74  -2.88 -42.59  -5.83
7  Q08  -5.82   8.85  e  p  u  30.82   7.79 -20.49 -41.73  -1.85
8  Q09  -6.36  -2.47  e  l  y  -2.79  21.72  -6.36 -27.26 -13.94
9  Q10 -16.34  -8.00  g  o  u   1.29  -7.36 -11.29  23.43  -2.02

In [216]:
x_unseen = df_unseen.drop(["id","x3","x4","x5"], axis=1)
x_unseen

      x1     x2     x6     x7     x8     x9    x10
0  -9.06  -6.24 -17.25  13.47  -9.97  -9.37   8.36
1 -10.93  -0.05  -5.69  -6.59  -8.48 -17.99  -8.84
2  -9.06   0.07 -26.56   7.69 -15.15  -9.59 -21.66
3   5.94  10.92  36.03  -2.95  22.84 -16.83   7.12
4  27.87  37.07   1.32   0.71 -17.56  -6.77   4.05
5  -9.49   1.17  31.70 -18.75   3.05   5.02  19.09
6   1.78  -1.09  41.81   8.74  -2.88 -42.59  -5.83
7  -5.82   8.85  30.82   7.79 -20.49 -41.73  -1.85
8  -6.36  -2.47  -2.79  21.72  -6.36 -27.26 -13.94
9 -16.34  -8.00   1.29  -7.36 -11.29  23.43  -2.02

In [260]:
my_model = RandomForestClassifier(n_estimators=288, max_depth=17)
my_model.fit(x, y)

RandomForestClassifier(max_depth=17, n_estimators=288)

In [261]:
y_unseen = my_model.predict(x_unseen)

n = 0
for i in y_unseen:
    print(f"{n + 1}. {y_unseen[n]}")
    n += 1

1. A
2. A
3. A
4. B
5. B
6. D
7. B
8. C
9. A
10. D