In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split

In [12]:
df = pd.read_csv("Ex2-Class-train.csv")
df

         id     x1    x2 x3 x4 x5     x6     x7     x8     x9    x10    y
0    id-001   4.98  0.55  e  n  y   8.29   1.29  -8.60 -20.77 -15.64  NaN
1    id-002   3.71  6.33  g  n  v   9.84  -1.12  -4.00 -18.82  -7.02    D
2    id-003  26.50   NaN  e  o  v  21.63  20.27  13.96   3.36   0.66    D
3    id-004  11.39  6.29  h  o  w   0.70  11.14   7.19  15.62   1.59    A
4    id-005   5.95  4.40  f  l  v  30.71   6.22  30.21   4.33  -4.27    D
..      ...    ...   ... .. .. ..    ...    ...    ...    ...    ...  ...
485  id-486  20.57  1.46  g  p  x -21.54  21.11 -52.55 -24.60   4.89    B
486  id-487  17.58 -3.73  e  l  w  -3.04 -21.11  38.80  29.34  -1.71    A
487  id-488   9.29  4.58  e  n  u  -9.01 -14.15   9.94   8.72  -2.94    C
488  id-489   7.59  9.15  f  p  w   4.35  16.51  -9.61  -4.13 -12.14    D
489  id-490  26.01 -0.67  i  m  w  19.17   2.95  31.00  12.19  -5.23    A

[490 rows x 12 columns]

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 490 entries, 0 to 489
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      480 non-null    object
 1   x1      480 non-null    float64
 2   x2      480 non-null    float64
 3   x3      480 non-null    object
 4   x4      480 non-null    object
 5   x5      480 non-null    object
 6   x6      480 non-null    float64
 7   x7      480 non-null    float64
 8   x8      480 non-null    float64
 9   x9      480 non-null    float64
 10  x10     480 non-null    float64
 11  y       480 non-null    object
dtypes: float64(7), object(5)
memory usage: 46.1+ KB

In [14]:
df.dropna(inplace=True)
df

         id     x1     x2 x3 x4 x5     x6     x7     x8     x9    x10  y
1    id-002   3.71   6.33  g  n  v   9.84  -1.12  -4.00 -18.82  -7.02  D
3    id-004  11.39   6.29  h  o  w   0.70  11.14   7.19  15.62   1.59  A
4    id-005   5.95   4.40  f  l  v  30.71   6.22  30.21   4.33  -4.27  D
5    id-006  14.07  -7.99  g  o  u -21.16  -9.17 -10.81   1.19   8.97  C
7    id-008  -9.31  34.84  f  l  y  -7.83 -34.83   0.54 -18.94  13.83  D
..      ...    ...    ... .. .. ..    ...    ...    ...    ...    ... ..
485  id-486  20.57   1.46  g  p  x -21.54  21.11 -52.55 -24.60   4.89  B
486  id-487  17.58  -3.73  e  l  w  -3.04 -21.11  38.80  29.34  -1.71  A
487  id-488   9.29   4.58  e  n  u  -9.01 -14.15   9.94   8.72  -2.94  C
488  id-489   7.59   9.15  f  p  w   4.35  16.51  -9.61  -4.13 -12.14  D
489  id-490  26.01  -0.67  i  m  w  19.17   2.95  31.00  12.19  -5.23  A

[383 rows x 12 columns]

In [15]:
df.reset_index(drop=True, inplace=True) 
df

         id     x1     x2 x3 x4 x5     x6     x7     x8     x9    x10  y
0    id-002   3.71   6.33  g  n  v   9.84  -1.12  -4.00 -18.82  -7.02  D
1    id-004  11.39   6.29  h  o  w   0.70  11.14   7.19  15.62   1.59  A
2    id-005   5.95   4.40  f  l  v  30.71   6.22  30.21   4.33  -4.27  D
3    id-006  14.07  -7.99  g  o  u -21.16  -9.17 -10.81   1.19   8.97  C
4    id-008  -9.31  34.84  f  l  y  -7.83 -34.83   0.54 -18.94  13.83  D
..      ...    ...    ... .. .. ..    ...    ...    ...    ...    ... ..
378  id-486  20.57   1.46  g  p  x -21.54  21.11 -52.55 -24.60   4.89  B
379  id-487  17.58  -3.73  e  l  w  -3.04 -21.11  38.80  29.34  -1.71  A
380  id-488   9.29   4.58  e  n  u  -9.01 -14.15   9.94   8.72  -2.94  C
381  id-489   7.59   9.15  f  p  w   4.35  16.51  -9.61  -4.13 -12.14  D
382  id-490  26.01  -0.67  i  m  w  19.17   2.95  31.00  12.19  -5.23  A

[383 rows x 12 columns]

In [16]:
# input
x = df.iloc[:, 1:-1]
# output
y = df.iloc[:, -1]

In [17]:
x = x.drop(["x3","x4","x5"], axis=1)

In [18]:
x

        x1     x2     x6     x7     x8     x9    x10
0     3.71   6.33   9.84  -1.12  -4.00 -18.82  -7.02
1    11.39   6.29   0.70  11.14   7.19  15.62   1.59
2     5.95   4.40  30.71   6.22  30.21   4.33  -4.27
3    14.07  -7.99 -21.16  -9.17 -10.81   1.19   8.97
4    -9.31  34.84  -7.83 -34.83   0.54 -18.94  13.83
..     ...    ...    ...    ...    ...    ...    ...
378  20.57   1.46 -21.54  21.11 -52.55 -24.60   4.89
379  17.58  -3.73  -3.04 -21.11  38.80  29.34  -1.71
380   9.29   4.58  -9.01 -14.15   9.94   8.72  -2.94
381   7.59   9.15   4.35  16.51  -9.61  -4.13 -12.14
382  26.01  -0.67  19.17   2.95  31.00  12.19  -5.23

[383 rows x 7 columns]

In [19]:
y

0      D
1      A
2      D
3      C
4      D
      ..
378    B
379    A
380    C
381    D
382    A
Name: y, Length: 383, dtype: object

In [20]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25)

print(f"Train data shape of x = {x_train.shape} and y = {y_train.shape}")
print(f"Test data shape of x = {x_test.shape} and y = {y_test.shape}")

Train data shape of x = (287, 7) and y = (287,)
Test data shape of x = (96, 7) and y = (96,)

**DECISION TREE**

In [21]:
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier

tree_model = DecisionTreeClassifier()
tree_model.fit(x_train, y_train)

DecisionTreeClassifier()

In [ ]:
print(tree.export_text(tree_model))

In [22]:
y_pred = tree_model.predict(x_test)
y_pred

array(['D', 'A', 'D', 'D', 'B', 'B', 'D', 'C', 'C', 'C', 'B', 'A', 'A',
       'A', 'B', 'C', 'A', 'A', 'C', 'D', 'D', 'D', 'D', 'C', 'A', 'C',
       'C', 'B', 'C', 'B', 'B', 'D', 'B', 'A', 'B', 'C', 'A', 'A', 'C',
       'A', 'B', 'D', 'D', 'C', 'B', 'A', 'B', 'B', 'A', 'D', 'A', 'D',
       'B', 'A', 'D', 'C', 'A', 'A', 'C', 'B', 'A', 'D', 'B', 'A', 'D',
       'A', 'C', 'C', 'C', 'A', 'A', 'B', 'D', 'B', 'C', 'A', 'D', 'D',
       'C', 'B', 'C', 'B', 'D', 'B', 'A', 'B', 'D', 'D', 'D', 'A', 'B',
       'D', 'A', 'D', 'A', 'B'], dtype=object)

In [23]:
from sklearn.metrics import accuracy_score

acc = accuracy_score(y_test, y_pred)
acc

0.7291666666666666

In [24]:
from sklearn.metrics import precision_recall_fscore_support

prf = precision_recall_fscore_support(y_test, y_pred, average = "weighted")
prf

(0.7329050925925925, 0.7291666666666666, 0.7286664124078311, None)

**RANDOM FORREST**

In [25]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(n_estimators=288, max_depth=17)
rf_model.fit(x_train, y_train)

RandomForestClassifier(max_depth=17, n_estimators=288)

In [26]:
y_pred = rf_model.predict(x_test)
y_pred

array(['B', 'A', 'D', 'D', 'D', 'B', 'D', 'C', 'C', 'C', 'C', 'A', 'A',
       'A', 'B', 'C', 'A', 'C', 'C', 'D', 'D', 'D', 'D', 'C', 'A', 'C',
       'B', 'B', 'C', 'B', 'B', 'D', 'B', 'A', 'C', 'C', 'A', 'A', 'C',
       'A', 'B', 'D', 'D', 'C', 'B', 'A', 'B', 'B', 'A', 'D', 'A', 'D',
       'B', 'A', 'D', 'B', 'A', 'A', 'A', 'B', 'C', 'D', 'B', 'A', 'D',
       'A', 'C', 'C', 'C', 'A', 'A', 'C', 'B', 'D', 'C', 'A', 'D', 'D',
       'C', 'B', 'C', 'B', 'D', 'B', 'A', 'B', 'B', 'D', 'D', 'A', 'B',
       'D', 'A', 'D', 'A', 'C'], dtype=object)

In [27]:
acc = accuracy_score(y_test, y_pred)
acc

0.7916666666666666

In [28]:
prf = precision_recall_fscore_support(y_test, y_pred, average = "weighted")
prf

(0.8019178511705686, 0.7916666666666666, 0.7925240929705216, None)

In [30]:
from sklearn.model_selection import KFold

kf = KFold(n_splits = 5)
acc_list = []

for train_index, test_index in kf.split(x):
  X_train, X_test = x.loc[train_index], x.loc[test_index]
  y_train, y_test = y.loc[train_index], y.loc[test_index]

  model = RandomForestClassifier(n_estimators=288, max_depth=17)
  model.fit(X_train, y_train)

  y_pred = model.predict(X_test)
  acc = accuracy_score(y_test, y_pred)
  acc_list.append(acc)

print("------------------------------------")
print("Random Forest")
print(" Mean Accuracy :", np.mean(acc_list))

------------------------------------
Random Forest
 Mean Accuracy : 0.7703349282296651

**Test Model**

In [31]:
df_unseen = pd.read_csv("Ex2-Class-unseen.csv")
df_unseen

    id     x1     x2 x3 x4 x5     x6     x7     x8     x9    x10
0  Q01  -2.24 -11.02  i  n  x  -2.43  -7.96  -2.64  -6.95  -0.66
1  Q02   4.39   4.57  g  n  v -23.36 -24.85  -7.10  -3.45   4.55
2  Q03  13.97 -19.62  h  o  v -11.54  -4.35  -7.56  -2.20   1.27
3  Q04 -26.99   1.47  h  m  y   5.15   8.84  17.05  28.64   3.49
4  Q05  11.27   8.28  f  l  x  17.51 -16.32  28.68  -2.76   1.35
5  Q06  11.74 -19.99  g  n  v   3.99   3.63   5.96   3.27  -8.77
6  Q07  16.73   3.39  h  n  y  18.50   5.54   8.22 -11.04 -12.54
7  Q08  -7.05  13.25  e  l  w   9.60 -20.72  32.16  11.25  -2.96
8  Q09  12.91   0.21  i  o  v  10.20  14.11  -5.99 -10.08  12.28
9  Q10  24.89   8.38  f  n  y  -3.53 -10.54   9.60   1.48  -6.34

In [32]:
x_unseen = df_unseen.drop(["id","x3","x4","x5"], axis=1)
x_unseen

      x1     x2     x6     x7     x8     x9    x10
0  -2.24 -11.02  -2.43  -7.96  -2.64  -6.95  -0.66
1   4.39   4.57 -23.36 -24.85  -7.10  -3.45   4.55
2  13.97 -19.62 -11.54  -4.35  -7.56  -2.20   1.27
3 -26.99   1.47   5.15   8.84  17.05  28.64   3.49
4  11.27   8.28  17.51 -16.32  28.68  -2.76   1.35
5  11.74 -19.99   3.99   3.63   5.96   3.27  -8.77
6  16.73   3.39  18.50   5.54   8.22 -11.04 -12.54
7  -7.05  13.25   9.60 -20.72  32.16  11.25  -2.96
8  12.91   0.21  10.20  14.11  -5.99 -10.08  12.28
9  24.89   8.38  -3.53 -10.54   9.60   1.48  -6.34

In [33]:
my_model = RandomForestClassifier(n_estimators=288, max_depth=17)
my_model.fit(x, y)

RandomForestClassifier(max_depth=17, n_estimators=288)

In [34]:
y_unseen = my_model.predict(x_unseen)

n = 0
for i in y_unseen:
    print(f"{n + 1}. {y_unseen[n]}")
    n += 1

1. C
2. C
3. C
4. C
5. D
6. A
7. D
8. B
9. D
10. B